### ISSUE TITLE
bin/bump-version.sh missing

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/pristine#13]
Cited here https://github.com/etclabscore/pristine/blob/f06cafd9131584e2b692068129a8d5ef23b9fdf2/VERSIONING.md#L28 and here https://github.com/etclabscore/pristine/blob/ffe5775db71b04c5b10ddfa2d4648c7253d3f1c6/RELEASING.md#L49.

Here's an over-the-top solution: https://github.com/truelab/git-bump-sh/blob/master/bin/bump
Here's a lighter-weight solution: https://gist.github.com/petervanderdoes/2877083

If we're managing version bumps programmatically, what should the tag messages be?

**Comment by shanejonas** [comment]
removed in #16
