### ISSUE TITLE
Release pipeline seems out of order... ?

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/pristine#14]
https://github.com/etclabscore/pristine/blob/master/RELEASING.md#release-pipeline

The current process is:
1. Build
2. Sign
3. Changelog
4. Version bump
5. Commit
6. Push
7. Draft release for targets (eg Github Releases)

Problems:
- (1) Sign should come after (4) Version bumping. For programs that are version-aware (eg. multigeth) doing otherwise will yield releases w/ "dirty" versions.
- (4) Version bump should come after (5) Commit. Otherwise tagged releases will not include the changelog changes.

Proposed solve:
1. Changelog
2. Commit
3. Version bump
4. Build
5. Sign
6. Push
7. Draft

Rel #11

**Comment by shanejonas** [comment]
theres some good steps here we can look at too: https://github.com/semantic-release/semantic-release#release-steps
