### ISSUE TITLE
Pristine repository [use the contents of this issue to create new issues on other repos]

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/pristine#33]
**Describe the feature you would like**
This repo should be using pristine to get a license, better baseline documentation, and encourage contributions.

**Describe the solution**
https://github.com/etclabscore/pristine#how-to-use-pristine-in-your-project

**Comment by BelfordZ** [comment]
wat?

**Comment by shanejonas** [comment]
lol this is just the ticket i’ve been using to copy to new repos to make tickets to pristine them
