### ISSUE TITLE
Make headings through out docs linkable

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/pristine#4]
example:
```
##### <a name="documentationChanges"></a> Documentation Changes
```

**Comment by shanejonas** [comment]
I think github has fixed this. seems to work with spaces for me in the current docs. Converts it to dashes and still links properly

![image](https://user-images.githubusercontent.com/364566/52074277-5d98b600-253e-11e9-9420-7ce2ce0723d5.png)
